techpack: audio: elliptic: Adapt to new wakeup source API fully
wakeup_source_init() and wakeup_source_trash() have been deprecated.
Adapt to the new wakeup_source_{register, unregister} functions to
fix the following compilation errors:

../techpack/audio/dsp/elliptic/elliptic.c:772:2: error: implicit declaration of function 'wakeup_source_init' [-Werror,-Wimplicit-function-declaration]
        wakeup_source_init(wake_source, "elliptic_wake_source");
        ^
../techpack/audio/dsp/elliptic/elliptic.c:772:2: note: did you mean 'wakeup_source_add'?
../include/linux/pm_wakeup.h:105:13: note: 'wakeup_source_add' declared here
extern void wakeup_source_add(struct wakeup_source *ws);
            ^
../techpack/audio/dsp/elliptic/elliptic.c:792:3: error: implicit declaration of function 'wakeup_source_trash' [-Werror,-Wimplicit-function-declaration]
                wakeup_source_trash(wake_source);
                ^

Subsequent to: b92d081fac ("techpack: audio: elliptic: adapt driver to kernel 4.19")

Change-Id: Id91fdaa8b68b2a292638415aee89c1f8b6f98fe8
Signed-off-by: pix106 <sbordenave@gmail.com>